export const puzzle1 = (lastInput, failSound, successSound, readyForInput) => {
  return [
    {
      id: 1,
      dialog: {
        expectedInput: 'username',
        responses: {
          successResponse: [
            `User: ${lastInput}`,
            `Jeff: Hey ${lastInput}, how are you doing today?`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `Jeff: Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 2,
      dialog: {
        expectedInput: '19.087.125',
        responses: {
          successResponse: [
            ` User: ${lastInput}`,
            () => successSound.play(),
            ` Jeff: Command Submission '${lastInput}' recognized`,
            'Jeff: locating',
            'Jeff: Connected to ChatRoom 15-68370223-23',
            `Jeff:  Password Required`,
            `Jeff:  Enter Authentication Code`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 3,
      dialog: {
        expectedInput: '3259241426',
        responses: {
          successResponse: [
            ` '${lastInput}'`,
            () => successSound.play(),
            ` Command Submission '${lastInput}' recognized`,
            'connecting',
            'Connected to ChatRoom 15-68370223-23',
            'typing',
            ` The C.I.A hot on our tail`,
            'typing',
            ` After years of ignorance`,
            'typing',
            ` Smith is going to pay for this`,
            'typing',
            ` What should we do?`,
            'typing',
            ` Nothing...`,
            'typing',
            ` They will be to late to stop us anyway`,
            'typing',
            ` The plan is already in motion`,
            'typing',
            ` ENCRYPTED URL: https://40353-36520-23634-27560`,
            ` COMMUNICATION CLOSED`,
            ` Enter IP Address you wish to connect`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 4,
      dialog: {
        expectedInput: '82.607.459',
        responses: {
          successResponse: [
            ` '${lastInput}'`,
            () => successSound.play(),
            ` Command Submission '${lastInput}' recognized`,
            'locating',
            'Connected to ChatRoom 15-68370223-23',
            ` Password protected`,
            ` ENTER Authentication code:`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 5,
      dialog: {
        expectedInput: '6502735770',
        hint: '102',
        responses: {
          successResponse: [
            ` '${lastInput}'`,
            () => successSound.play(),
            ` Command Submission '${lastInput}' recognized`,
            'connecting',
            'Connected to ChatRoom 15-68370223-23',
            'typing',
            ` Quick`,
            'typing',
            ` It wont take him long to find us again`,
            'typing',
            ` We are too close to let him stop us`,
            'typing',
            ` He's here already`,
            'typing',
            ` Go to this chat room. I will meet you there.`,
            'typing',
            ` ENCRYPTED URL: https://66737-26553-26594-46592`,
            ` USER @Ax7 DISCONNECTED`,
            'typing',
            ` You are too close for comfort C.I.A man`,
            'typing',
            ` Do you really think you have what it takes to catch me?`,
            'typing',
            ` How long have you been trying already?`,
            'typing',
            ` Best to just give up now.`,
            ` ALABASTER DISCONNECTED`,
            ` CHATROOM CLOSED`,
            ` YOU HAVE BEEN DISCONNECTED`,
            ` Enter IP Address you wish to connect`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 6,
      dialog: {
        expectedInput: '62.746.271',
        hint: '103',
        responses: {
          successResponse: [
            ` '${lastInput}'`,
            () => successSound.play(),
            ` Command Submission '${lastInput}' recognized`,
            'locating',
            'Connected to ChatRoom 15-68370223-23',
            ` Password protected`,
            ` ENTER Authentication code:`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 7,
      dialog: {
        expectedInput: '9235613951',
        hint: '104',
        responses: {
          successResponse: [
            ` '${lastInput}'`,
            () => successSound.play(),
            ` Command Submission '${lastInput}' recognized`,
            'connecting',
            'Connected to ChatRoom 15-68370223-23',
            'typing',
            ` Now go. I've left clues for you to find me.`,
            'typing',
            ` Oh... Look who's here`,
            ` USER @Ax7 DISCONNECTED`,
            'typing',
            ` That took you longer than I expected`,
            'typing',
            ` Maybe I don't need to worry at all`,
            'typing',
            ` I wager my disciple can find me hours before you do.`,
            'typing',
            ` By that time it will be too late for you to do anything.`,
            'typing',
            ` Except watch it all crumble`,
            'typing',
            ` Alright... I grow tired of this`,
            'typing',
            ` ENCRYPTED URL: https://20693-10782-40621-12479`,
            ` ALABASTER DISCONNECTED`,
            ` CHATROOM CLOSED`,
            ` YOU HAVE BEEN DISCONNECTED`,
            ` LOGIN`,
            ` PLEASE ENTER USERNAME, THEN PRESS ENTER`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 8,
      dialog: {
        expectedInput: 'DontForgetAgain',
        hint: '105',
        responses: {
          successResponse: [
            ` '${lastInput}'`,
            () => successSound.play(),
            ` Command Submission '${lastInput}' recognized`,
            ` PLEASE ENTER PASSWORD`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 9,
      dialog: {
        expectedInput: 'FindTheYellowFlower',
        hint: '106',
        responses: {
          successResponse: [
            ` '${lastInput}'`,
            () => successSound.play(),
            ` Command Submission '${lastInput}' recognized`,
            ` Logged in`,
            ` Welcome DontForgetAgain`,
            ` INBOX:`,
            ` Message 1: Phone Code: 712`,
            ` Message 2: https://10109-37583-28534-49452`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            ` Command Submission '${lastInput}' Not Recognized`,
          ],
        },
      },
    },
    {
      id: 10,
      dialog: {
        expectedInput: "you'llneverGue$$",
        responses: {
          successResponse: [''],
          failureResponse: [() => failSound.play()],
        },
      },
    },
  ];
};
