import {
  userInputPrefix,
  outputPrefix,
  alabasterOutput,
  ax7Output,
  spacer,
} from 'utils';

export const puzzle1 = (
  lastInput,
  username,
  password,
  failSound,
  successSound,
  readyForInput,
  setGlitching
  // returnUsername
) => {
  return [
    {
      id: 1,
      dialog: {
        expectedInput: '3512076170',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            'connecting',
            spacer,
            `${ax7Output} You think we have a mole?`,
            `${alabasterOutput} I think somone is feeding info to the CIA.`,
            `${alabasterOutput} There has been minimal movement on their servers... until today.`,
            `${alabasterOutput} and all at once...`,
            `${ax7Output} Who do you think it is?`,
            `${alabasterOutput} I'm busy with bigger things.`,
            `${alabasterOutput} Have you seen anything suspicious?`,
            `${ax7Output} Smith has been...`,
            `${ax7Output} Less invested lately.`,
            `${alabasterOutput} wait...`,
            `${alabasterOutput} Someone else is here.`,
            `${alabasterOutput} This communication has been compromised.`,
            `${alabasterOutput} Change chatrooms.`,
            `${alabasterOutput} https://12406-13796-93659-37402`,
            `${outputPrefix} COMMUNICATION CLOSED`,
            spacer,
            `${outputPrefix} Enter IP Address you wish to connect`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 2,
      dialog: {
        expectedInput: '19.087.125',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            'connecting',
            spacer,
            `${alabasterOutput} The C.I.A hot on our tail`,
            `${alabasterOutput} After years of ignorance`,
            `${alabasterOutput} Smith is going to pay for this`,
            `${ax7Output} What should we do?`,
            `${alabasterOutput} Nothing...`,
            `${alabasterOutput} They will be to late to stop us anyway`,
            `${alabasterOutput} The plan is already in motion`,
            `${alabasterOutput} ENCRYPTED URL: https://40353-36520-23634-27560`,
            `${outputPrefix} COMMUNICATION CLOSED`,
            spacer,
            `${outputPrefix} Enter IP Address you wish to connect`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 3,
      dialog: {
        expectedInput: '82.607.459',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            'connecting',
            spacer,
            `${outputPrefix} Password protected`,
            `${outputPrefix} ENTER Authentication code:`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 4,
      dialog: {
        expectedInput: '6502735770',
        hint: '102',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            'connecting',
            spacer,
            `${alabasterOutput} Quick`,
            `${alabasterOutput} It wont take him long to find us again`,
            `${alabasterOutput} We are too close to let him stop us`,
            `${alabasterOutput} He's here already`,
            `${alabasterOutput} Go to this chat room. I will meet you there.`,
            `${alabasterOutput} ENCRYPTED URL: https://66737-26553-26594-46592`,
            `${outputPrefix} USER @Ax7 DISCONECTED`,
            `${alabasterOutput} You are too close for comfort C.I.A man`,
            `${alabasterOutput} Do you realy think you have what it takes to catch me?`,
            `${alabasterOutput} How long have you been trying already?`,
            `${alabasterOutput} Best to just give up now.`,
            `${outputPrefix} ALABASTER DICONNECTED`,
            `${outputPrefix} CHATROOM CLOSED`,
            `${outputPrefix} YOU HAVE BEEN DISCONNECTED`,
            spacer,
            `${outputPrefix} Enter IP Address you wish to connect`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 5,
      dialog: {
        expectedInput: '62.746.271',
        hint: '103',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            'connecting',
            `${outputPrefix} Password protected`,
            `${outputPrefix} ENTER Authentication code:`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 6,
      dialog: {
        expectedInput: '651697597',
        hint: '104',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            'connecting',
            spacer,
            `${alabasterOutput} Now go. I've left clues for you to find me.`,
            `${alabasterOutput} Oh... Look who's here`,
            `${outputPrefix} USER @Ax7 DISCONECTED`,
            `${alabasterOutput} That took you longer than I expected`,
            `${alabasterOutput} Maybe I don't need to worry at all`,
            `${alabasterOutput} I wager my disciple can find me hours before you do.`,
            `${alabasterOutput} By that time it will be too late for you to do anything.`,
            `${alabasterOutput} Except watch it all crumble`,
            `${alabasterOutput} Alright... I grow tired of this`,
            `${alabasterOutput} ENCRYPTED URL: https://20693-10782-40621-12479`,
            `${outputPrefix} ALABASTER DICONNECTED`,
            `${outputPrefix} CHATROOM CLOSED`,
            `${outputPrefix} YOU HAVE BEEN DISCONNECTED`,
            spacer,
            `${outputPrefix} LOGIN`,
            `${outputPrefix} PLEASE ENTER USERNAME, THEN PRESS ENTER`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 7,
      dialog: {
        expectedInput: 'DontForgetAgain',
        hint: '105',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            'connecting',
            spacer,
            `${outputPrefix} PLEASE ENTER PASSWORD`,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
    {
      id: 8,
      dialog: {
        expectedInput: 'FindTheYellowFlower',
        hint: '106',
        responses: {
          successResponse: [
            () => successSound.play(),
            `${userInputPrefix} '${lastInput}'`,
            `${outputPrefix} Command Submission '${lastInput}' recognized`,
            spacer,
            `${outputPrefix} Logged in`,
            `${outputPrefix} Welcome DontForgetAgain`,
            `${outputPrefix} INBOX:`,
            `${outputPrefix} Message 1: Phone Code: 712`,
            `${outputPrefix} Message 2: https://10109-37583-28534-49452`,
            spacer,
            () => readyForInput.play(),
          ],
          failureResponse: [
            () => failSound.play(),
            `${outputPrefix} Command Submission '${lastInput}' Not Recognized`,
            spacer,
            () => readyForInput.play(),
          ],
        },
      },
    },
  ];
};
